exporter_endpoint = "http://localhost:7281"
service_name = "frog-server"

[server]
port = 8000
url = "0.0.0.0"

[pg]
url = "postgres://postgres:changeme@127.0.0.1:5432/postgres"
max_size = 10

[phantom_server]
crs_seed = "crs_seed_32_bytes_123456789_123456789_123456789"
participant_number = 2

[worker]
schema = "worker"
