exporter_endpoint = "http://localhost:7281"
service_name = "frog-worker"

[server]
port = 8003
url = "0.0.0.0"

[pg]
url = "postgres://postgres:changeme@127.0.0.1:5432/postgres"
max_size = 10

[worker]
concurrent = 3
schema = "worker"
