service_name = "{{$.name}}"
exporter_endpoint = "{{$.exporter_endpoint}}"

[server]
url = "0.0.0.0"
port = {{$.http_port}}

[pg]
url = "{{$.pg_url}}"
max_size = 10

[phantom_server]
crs_seed = "{{$.crs_seed}}"
participant_number = {{$.participant_number}}

[worker]
schema = "{{$.schema}}"
