exporter_endpoint = "http://0.0.0.0:7281"
service_name = "{{$.name}}"

[server]
url = "0.0.0.0"
port = {{$.http_port}}

[pg]
url = "{{$.pg_url}}"
max_size = 10

[worker]
concurrent = {{$.concurrent}}
schema = "{{$.schema}}"
