[package]
name = "phantom"
version = "0.0.1"
edition = "2021"

[dependencies]
bincode = { workspace = true }
itertools = { workspace = true }
phantom-zone-evaluator = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
